apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  namespace: hbase-cluster
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
    - port: 7000
      name: prometheus
  clusterIP: None
  selector:
    app: zk
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  namespace: hbase-cluster
spec:
  selector:
    matchLabels:
      app: zk
  serviceName: zk-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
        - name: main
          imagePullPolicy: Always
          image: "192.168.9.128:5000/jayeljj/zookeeper:3.6.3"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: ZOO_CFG_EXTRA
              value: metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider
            - name: ZOO_4LW_COMMANDS_WHITELIST
              value: "ruok"
            - name: ZOO_SERVERS
              value: "server.1=zk-0.zk-hs.hbase-cluster.svc.cluster.local:2888:3888;2181 server.2=zk-1.zk-hs.hbase-cluster.svc.cluster.local:2888:3888;2181 server.3=zk-2.zk-hs.hbase-cluster.svc.cluster.local:2888:3888;2181"
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "/zookeeper-ready.sh 2181"
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "/zookeeper-ready.sh 2181"
            initialDelaySeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
