apiVersion: v1
kind: Service
metadata:
  name: hbase-rs-svc
  namespace: hbase-cluster
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 16020
      name: rpc
      targetPort: 16020
  selector:
    app: hbase-rs
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-rs
  namespace: hbase-cluster
spec:
  selector:
    matchLabels:
      app: hbase-rs
  serviceName: hbase-rs-svc
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hbase-rs
    spec:
      terminationGracePeriodSeconds: 100
      containers:
        - name: main
          imagePullPolicy: Always
          image: "192.168.9.128:5000/jayeljj/hbase-regionserver:2.4.15"
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
          envFrom:
            - configMapRef:
                name: hbase-env
          env:
            - name: HBASE_HEAPSIZE
              value: "1G"
            - name: HBASE_ROOT_LOGGER
              value: "INFO,console,RFA"
          readinessProbe:
            exec:
              command:
                - /health.sh
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /rs-status
              port: 16030
            initialDelaySeconds: 10
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                # call graceful_stop.sh with servername to move regions in current server to another server
                command: ["/bin/sh", "-c", 'curl -s "0:16030/rs-status" | grep "HBase Region Server" | grep -o -E "([0-9]+\.)[0-9]+" | xargs -I{} graceful_stop.sh {}']
          volumeMounts:
            - name: logs
              mountPath: /opt/hbase-2.4.15/logs
      volumes:
        - name: logs
          emptyDir: {}