apiVersion: v1
kind: Service
metadata:
  name: hbase-web-svc
  namespace: hbase-cluster
spec:
  type: NodePort
  ports:
    - port: 16010
      name: http
      targetPort: 16010
      nodePort: 32719
  selector:
    app: hbase-master
---

apiVersion: v1
kind: Service
metadata:
  name: hbase-master-svc
  namespace: hbase-cluster
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 16000
      name: rpc
      targetPort: 16000
  selector:
    app: hbase-master
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-master
  namespace: hbase-cluster
spec:
  selector:
    matchLabels:
      app: hbase-master
  serviceName: hbase-master-svc
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hbase-master
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - hbase-master
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: main
          imagePullPolicy: Always
          image: "192.168.9.128:5000/jayeljj/hbase-master:2.4.15"
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: hbase-env
          env:
            - name: HBASE_ROOT_LOGGER
              value: "INFO,console,RFA"
          readinessProbe:
            exec:
              command:
                - /health.sh
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - /health.sh
            initialDelaySeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: logs
              mountPath: /opt/hbase-2.4.15/logs
      volumes:
        - name: logs
          emptyDir: {}